### ISSUE TITLE
Disable pow process logs

### ISSUE THREAD

**Issue by vladikus10** [iota-pico/pow-nodejs#4]
Is there a way to disable the pow process logs? this ones: 
```
Getting platforms... 
Cannot get the number of OpenCL platforms available. E:-1
Thread Hashing...
I: Starting search threads.
I: Found threads. Returning.
Thread Hashing...
I: Starting search threads.
I: Found threads. Returning.
Thread Hashing...
I: Starting search threads.
I: Found threads. Returning.
Thread Hashing...
I: Starting search threads.
I: Found threads. Returning.
Thread Hashing...
I: Starting search threads.
I: Found threads. Returning.
```
Since I'm using the module in a terminal app, they are bit in the way.

**Comment by obany** [comment]
My code uses the official https://github.com/iotaledger/curl.lib.js c library to do the pow, the process logs come from the c libs, unfortunately there is no way to disable them without creating custom versions of the lib.

**Comment by vladikus10** [comment]
mhm, I see. Thank you for the quick reply!
